/api-comments/entry/11/forum/3
/api-courses/course/741
/api-courses/delete/5
/api-courses/edit
/api-courses/edit/add-attenders/course/6
/api-courses/new
/api-courses/user/741
/api-entries/forum/3
/api-files/3
/api-forum/edit/3
/api-logIn
/api-logOut
/api-sessions/course/3
/api-users/changePassword
/api-users/new
