rest_api_regex("^(http://[^/]+)?/api/v1/adminbasicservice/adminbasic/configs$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminbasicservice/adminbasic/configs/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminbasicservice/adminbasic/contacts$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminbasicservice/adminbasic/contacts/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminbasicservice/adminbasic/prices$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminbasicservice/adminbasic/stations$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminbasicservice/adminbasic/trains$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminbasicservice/adminbasic/trains/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminbasicservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminorderservice/adminorder$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminorderservice/adminorder/[^/]+/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminorderservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminrouteservice/adminroute$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminrouteservice/adminroute/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminrouteservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/admintravelservice/admintravel$").
rest_api_regex("^(http://[^/]+)?/api/v1/admintravelservice/admintravel/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/admintravelservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminuserservice/users$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminuserservice/users/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminuserservice/users/user_id$").
rest_api_regex("^(http://[^/]+)?/api/v1/assuranceservice/assurances$").
rest_api_regex("^(http://[^/]+)?/api/v1/assuranceservice/assurances/types$").
rest_api_regex("^(http://[^/]+)?/api/v1/assuranceservice/assurances/1/order_id$").
rest_api_regex("^(http://[^/]+)?/api/v1/assuranceservice/assurances/assuranceid/order_id$").
rest_api_regex("^(http://[^/]+)?/api/v1/assuranceservice/assurances/assurance_id/order_id/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/assuranceservice/assurances/orderid/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/auth$").
rest_api_regex("^(http://[^/]+)?/api/v1/auth/hello$").
rest_api_regex("^(http://[^/]+)?/api/v1/basicservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/basicservice/basic/travel$").
rest_api_regex("^(http://[^/]+)?/api/v1/basicservice/basic/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/cancelservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/cancelservice/cancel/order_id/login_id$").
rest_api_regex("^(http://[^/]+)?/api/v1/cancelservice/cancel/refound/order_id$").
rest_api_regex("^(http://[^/]+)?/api/v1/configservice/configs$").
rest_api_regex("^(http://[^/]+)?/api/v1/configservice/configs/config_name$").
rest_api_regex("^(http://[^/]+)?/api/v1/configservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/consignpriceservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/consignpriceservice/consignprice$").
rest_api_regex("^(http://[^/]+)?/api/v1/consignpriceservice/consignprice/config$").
rest_api_regex("^(http://[^/]+)?/api/v1/consignpriceservice/consignprice/price$").
rest_api_regex("^(http://[^/]+)?/api/v1/consignpriceservice/consignprice/1.0/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/consignservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/consignservice/consigns$").
rest_api_regex("^(http://[^/]+)?/api/v1/consignservice/consigns/account/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/consignservice/consigns/order/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/consignservice/consigns/consignee$").
rest_api_regex("^(http://[^/]+)?/api/v1/consignservice/consigns/order/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/consignservice/consigns/account/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/contactservice/contacts$").
rest_api_regex("^(http://[^/]+)?/api/v1/contactservice/contacts/admin$").
rest_api_regex("^(http://[^/]+)?/api/v1/contactservice/contacts/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/contactservice/contacts/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/contactservice/contacts/account/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/contactservice/contacts/welcome/account/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/contactservice/contacts/welcome/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/executeservice/execute/collected/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/executeservice/execute/execute/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/executeservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/foodmapservice/foodstores$").
rest_api_regex("^(http://[^/]+)?/api/v1/foodmapservice/foodstores/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/foodmapservice/foodstores/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/foodmapservice/trainfoods$").
rest_api_regex("^(http://[^/]+)?/api/v1/foodmapservice/trainfoods/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/foodmapservice/trainfoods/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/foodservice/foods/[^/]+/[^/]+/[^/]+/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/foodservice/orders$").
rest_api_regex("^(http://[^/]+)?/api/v1/foodservice/orders/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/foodservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/inside_pay_service/inside_payment$").
rest_api_regex("^(http://[^/]+)?/api/v1/inside_pay_service/inside_payment/account$").
rest_api_regex("^(http://[^/]+)?/api/v1/inside_pay_service/inside_payment/money$").
rest_api_regex("^(http://[^/]+)?/api/v1/inside_pay_service/inside_payment/payment$").
rest_api_regex("^(http://[^/]+)?/api/v1/inside_pay_service/inside_payment/difference$").
rest_api_regex("^(http://[^/]+)?/api/v1/inside_pay_service/inside_payment/drawback/[^/]+/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/inside_pay_service/inside_payment/[^/]+/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/inside_pay_service/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/notifyservice/notification/order_cancel_success$").
rest_api_regex("^(http://[^/]+)?/api/v1/notifyservice/notification/order_changed_success$").
rest_api_regex("^(http://[^/]+)?/api/v1/notifyservice/notification/order_create_success$").
rest_api_regex("^(http://[^/]+)?/api/v1/notifyservice/notification/preserve_success$").
rest_api_regex("^(http://[^/]+)?/api/v1/notifyservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/admin$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/orderPay/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/price/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/query$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/refresh$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/status/[^/]+/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/tickets$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/order$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/order/admin$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/order/query$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/order/refresh$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/order/tickets$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/order/orderPay/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/order/price/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/order/status/[^/]+/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/order/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/paymentservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/paymentservice/payment$").
rest_api_regex("^(http://[^/]+)?/api/v1/paymentservice/payment/money$").
rest_api_regex("^(http://[^/]+)?/api/v1/preserveotherservice/preserveOther$").
rest_api_regex("^(http://[^/]+)?/api/v1/preserveotherservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/preserveservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/preserveservice/preserve$").
rest_api_regex("^(http://[^/]+)?/api/v1/priceservice/prices$").
rest_api_regex("^(http://[^/]+)?/api/v1/priceservice/prices/[^/]+/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/priceservice/prices/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/rebookservice/rebook$").
rest_api_regex("^(http://[^/]+)?/api/v1/rebookservice/rebook/difference$").
rest_api_regex("^(http://[^/]+)?/api/v1/rebookservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/routeplanservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/routeplanservice/routePlan/quickestRoute$").
rest_api_regex("^(http://[^/]+)?/api/v1/routeplanservice/routePlan/minStopStations$").
rest_api_regex("^(http://[^/]+)?/api/v1/routeplanservice/routePlan/cheapestRoute$").
rest_api_regex("^(http://[^/]+)?/api/v1/routeservice/routes$").
rest_api_regex("^(http://[^/]+)?/api/v1/routeservice/routes/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/routeservice/routes/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/routeservice/routes/[^/]+/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/seatservice/seats$").
rest_api_regex("^(http://[^/]+)?/api/v1/seatservice/seats/left_tickets$").
rest_api_regex("^(http://[^/]+)?/api/v1/seatservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/securityservice/securityConfigs$").
rest_api_regex("^(http://[^/]+)?/api/v1/securityservice/securityConfigs/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/securityservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/stationservice/stations$").
rest_api_regex("^(http://[^/]+)?/api/v1/stationservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/stationservice/stations/idlist$").
rest_api_regex("^(http://[^/]+)?/api/v1/stationservice/stations/namelist$").
rest_api_regex("^(http://[^/]+)?/api/v1/stationservice/stations/[^/]+/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/ticketinfoservice/ticketinfo$").
rest_api_regex("^(http://[^/]+)?/api/v1/ticketinfoservice/ticketinfo/name$").
rest_api_regex("^(http://[^/]+)?/api/v1/ticketinfoservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/trainservice/trains$").
rest_api_regex("^(http://[^/]+)?/api/v1/trainservice/trains/id$").
rest_api_regex("^(http://[^/]+)?/api/v1/trainservice/trains/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/trainservice/trains/wrong_id$").
rest_api_regex("^(http://[^/]+)?/api/v1/travel2service/admin_trip$").
rest_api_regex("^(http://[^/]+)?/api/v1/travel2service/routes/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/travel2service/train_types/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/travel2service/trips$").
rest_api_regex("^(http://[^/]+)?/api/v1/travel2service/trips/left$").
rest_api_regex("^(http://[^/]+)?/api/v1/travel2service/trips/routes$").
rest_api_regex("^(http://[^/]+)?/api/v1/travel2service/trips/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/travel2service/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelplanservice/travelPlan/cheapest$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelplanservice/travelPlan/minStation$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelplanservice/travelPlan/quickest$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelplanservice/travelPlan/transferResult$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelplanservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelservice/admin_trip$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelservice/routes/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelservice/train_types/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelservice/trip_detail$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelservice/trips$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelservice/trips/left$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelservice/trips/routes$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelservice/trips/trip_id$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/users$").
rest_api_regex("^(http://[^/]+)?/api/v1/users/hello$").
rest_api_regex("^(http://[^/]+)?/api/v1/users/login$").
rest_api_regex("^(http://[^/]+)?/api/v1/users/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/userservice/users$").
rest_api_regex("^(http://[^/]+)?/api/v1/userservice/users/hello$").
rest_api_regex("^(http://[^/]+)?/api/v1/userservice/users/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/userservice/users/id/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/userservice/users/register$").
rest_api_regex("^(http://[^/]+)?/api/v1/userservice/users/user_name$").
rest_api_regex("^(http://[^/]+)?/api/v1/verifycode/generate$").
rest_api_regex("^(http://[^/]+)?/api/v1/verifycode/verify/verifyCode$").