rest_api_regex("^(http://[^/]+)?/api/v1/adminbasicservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminrouteservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/adminuserservice/users/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/basicservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/inside_pay_service/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/notifyservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/paymentservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/rebookservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/routeservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/securityservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/ticketinfoservice/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/trainservice/trains/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/travel2service/welcome$").
rest_api_regex("^(http://[^/]+)?/api/v1/contactservice/contacts$").
rest_api_regex("^(http://[^/]+)?/api/v1/contactservice/contacts/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/stationservice/stations$").
rest_api_regex("^(http://[^/]+)?/api/v1/trainservice/trains$").
rest_api_regex("^(http://[^/]+)?/api/v1/configservice/configs$").
rest_api_regex("^(http://[^/]+)?/api/v1/configservice/configs/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/priceservice/prices$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderservice/order/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/orderOtherService/orderOther/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/routeservice/routes/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/routeservice/routes$").
rest_api_regex("^(http://[^/]+)?/api/v1/travelservice/trips/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/travel2service/trips/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/userservice/users/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/verifycode/verify/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/stationservice/stations/[^/]+/[^/]+$").
rest_api_regex("^(http://[^/]+)?/api/v1/trainservice/trains/[^/]+$").

