^\/api\-comments\/entry\/.*\/forum\/.*$
^\/api\-courses\/user\/.*$
^\/api\-courses\/course\/.*$
^\/api\-courses\/new$
^\/api\-courses\/edit$
^\/api\-courses\/delete\/.*$
^\/api\-courses\/edit\/add\-attenders\/course\/.*$
^\/api\-courses\/edit\/delete\-attenders$
^\/api\-entries\/forum\/.*$
^\/api\-load\-files\/upload\/course\/.*\/file\-group\/.*$
^\/api\-load\-files\/course\/.*\/download\/.*$
^\/api\-load\-files\/upload\/picture\/.*$
^\/api\-load\-files\/upload\/course\/.*\/comment\/.*$
^\/api\-files\/.*$
^\/api\-files\/edit\/file\-group\/course\/.*$
^\/api\-files\/delete\/file\-group\/.*\/course\/.*$
^\/api\-files\/edit\/file\-order\/course\/.*\/file\/.*\/from\/.*\/to\/.*\/pos\/.*$
^\/api\-files\/edit\/file\/file\-group\/.*\/course\/.*$
^\/api\-files\/delete\/file\/.*\/file\-group\/.*\/course\/.*$
^\/api\-file\-reader\/upload\/course\/.*$
^\/api\-forum\/edit\/.*$
^\/api\-logIn$
^\/api\-logOut$
^\/api\-sessions\/course\/.*$
^\/api\-sessions\/edit$
^\/api\-sessions\/delete\/.*$