rest_api_regex("^\\/api\\-comments\\/entry\\/.*\\/forum\\/.*$").
rest_api_regex("^\\/api\\-courses\\/user\\/.*$").
rest_api_regex("^\\/api\\-courses\\/course\\/.*$").
rest_api_regex("^\\/api\\-courses\\/new$").
rest_api_regex("^\\/api\\-courses\\/edit$").
rest_api_regex("^\\/api\\-courses\\/delete\\/.*$").
rest_api_regex("^\\/api\\-courses\\/edit\\/add\\-attenders\\/course\\/.*$").
rest_api_regex("^\\/api\\-courses\\/edit\\/delete\\-attenders$").
rest_api_regex("^\\/api\\-entries\\/forum\\/.*$").
rest_api_regex("^\\/api\\-load\\-files\\/upload\\/course\\/.*\\/file\\-group\\/.*$").
rest_api_regex("^\\/api\\-load\\-files\\/course\\/.*\\/download\\/.*$").
rest_api_regex("^\\/api\\-load\\-files\\/upload\\/picture\\/.*$").
rest_api_regex("^\\/api\\-load\\-files\\/upload\\/course\\/.*\\/comment\\/.*$").
rest_api_regex("^\\/api\\-files\\/.*$").
rest_api_regex("^\\/api\\-files\\/edit\\/file\\-group\\/course\\/.*$").
rest_api_regex("^\\/api\\-files\\/delete\\/file\\-group\\/.*\\/course\\/.*$").
rest_api_regex("^\\/api\\-files\\/edit\\/file\\-order\\/course\\/.*\\/file\\/.*\\/from\\/.*\\/to\\/.*\\/pos\\/.*$").
rest_api_regex("^\\/api\\-files\\/edit\\/file\\/file\\-group\\/.*\\/course\\/.*$").
rest_api_regex("^\\/api\\-files\\/delete\\/file\\/.*\\/file\\-group\\/.*\\/course\\/.*$").
rest_api_regex("^\\/api\\-file\\-reader\\/upload\\/course\\/.*$").
rest_api_regex("^\\/api\\-forum\\/edit\\/.*$").
rest_api_regex("^\\/api\\-logIn$").
rest_api_regex("^\\/api\\-logOut$").
rest_api_regex("^\\/api\\-sessions\\/course\\/.*$").
rest_api_regex("^\\/api\\-sessions\\/edit$").
rest_api_regex("^\\/api\\-sessions\\/delete\\/.*$").
