invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 3, 'com/fullteaching/backend/e2e/rest/UserRestTest:testChangeUserPassword:()V', 4, 2, [pointsTo('this', 'Object[10460]')], 'com/fullteaching/backend/e2e/rest/UserRestTest:createUser:(Ljava/lang/String;)I', ['["unique2@gmail.com", "Mock66666", "fakeUser", "IGNORE"]']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 13, 'com/fullteaching/backend/e2e/rest/UserRestTest:createUser:(Ljava/lang/String;)I', 17, 3, [pointsTo('this', 'Object[10460]')], 'com/fullteaching/backend/utils/HttpApiClient:<init>:(Lorg/apache/http/impl/client/HttpClientBuilder;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V', [null, 5000, '/api-users/new', null, null, 'Object[10482]']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 15, 'com/fullteaching/backend/utils/HttpApiClient:<init>:(Lorg/apache/http/impl/client/HttpClientBuilder;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V', 1, 4, [pointsTo('this', 'Object[10460]')], 'java/lang/Object:<init>:()V', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 24, 'com/fullteaching/backend/utils/HttpApiClient:<init>:(Lorg/apache/http/impl/client/HttpClientBuilder;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V', 77, 6, [pointsTo('this', 'Object[10460]')], 'java/lang/StringBuilder:<init>:()V', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 27, 'java/lang/StringBuilder:<init>:()V', 3, 7, [pointsTo('this', 'Object[10460]')], 'java/lang/AbstractStringBuilder:<init>:(I)V', [16]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 29, 'java/lang/AbstractStringBuilder:<init>:(I)V', 1, 8, [pointsTo('this', 'Object[10460]')], 'java/lang/Object:<init>:()V', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 38, 'com/fullteaching/backend/utils/HttpApiClient:<init>:(Lorg/apache/http/impl/client/HttpClientBuilder;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V', 82, 12, [pointsTo('this', 'Object[10460]')], 'java/lang/StringBuilder:append:(Ljava/lang/String;)Ljava/lang/StringBuilder;', [null]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 41, 'java/lang/StringBuilder:append:(Ljava/lang/String;)Ljava/lang/StringBuilder;', 2, 13, [pointsTo('this', 'Object[10460]')], 'java/lang/AbstractStringBuilder:append:(Ljava/lang/String;)Ljava/lang/AbstractStringBuilder;', [11]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 45, 'java/lang/AbstractStringBuilder:append:(Ljava/lang/String;)Ljava/lang/AbstractStringBuilder;', 10, 14, [pointsTo('this', 'Object[10460]')], 'java/lang/String:length:()I', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 56, 'java/lang/AbstractStringBuilder:append:(Ljava/lang/String;)Ljava/lang/AbstractStringBuilder;', 21, 16, [pointsTo('this', 'Object[10460]')], 'java/lang/AbstractStringBuilder:ensureCapacityInternal:(I)V', [32]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 71, 'java/lang/AbstractStringBuilder:append:(Ljava/lang/String;)Ljava/lang/AbstractStringBuilder;', 35, 18, [pointsTo('this', 'Object[10460]')], 'java/lang/String:getChars:(II[CI)V', [0, 11, 'Object[10479]', 21]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 111, 'java/lang/AbstractStringBuilder:append:(Ljava/lang/String;)Ljava/lang/AbstractStringBuilder;', 5, 24, [pointsTo('this', 'Object[10460]')], 'java/lang/AbstractStringBuilder:appendNull:()Ljava/lang/AbstractStringBuilder;', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 119, 'java/lang/AbstractStringBuilder:appendNull:()Ljava/lang/AbstractStringBuilder;', 9, 25, [pointsTo('this', 'Object[10460]')], 'java/lang/AbstractStringBuilder:ensureCapacityInternal:(I)V', [12]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 159, 'com/fullteaching/backend/utils/HttpApiClient:<init>:(Lorg/apache/http/impl/client/HttpClientBuilder;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V', 89, 30, [pointsTo('this', 'Object[10460]')], 'java/lang/StringBuilder:toString:()Ljava/lang/String;', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 167, 'java/lang/StringBuilder:toString:()Ljava/lang/String;', 13, 31, [pointsTo('this', 'Object[10460]')], 'java/lang/String:<init>:([CII)V', ['Object[10479]', 0, 32]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 169, 'java/lang/String:<init>:([CII)V', 1, 32, [pointsTo('this', 'Object[10460]')], 'java/lang/Object:<init>:()V', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 187, 'java/lang/String:<init>:([CII)V', 75, 34, [pointsTo('this', 'Object[10460]')], 'java/util/Arrays:copyOfRange:([CII)[C', [32, 32, 'Object[10481]']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 206, 'java/util/Arrays:copyOfRange:([CII)[C', 54, 35, [pointsTo('this', 'Object[10460]')], 'java/lang/Math:min:(II)I', [34, 32]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 218, 'com/fullteaching/backend/utils/HttpApiClient:<init>:(Lorg/apache/http/impl/client/HttpClientBuilder;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V', 92, 40, [pointsTo('this', 'Object[10460]')], 'org/apache/http/client/utils/URIBuilder:<init>:(Ljava/lang/String;)V', ['https://null']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 220, 'org/apache/http/client/utils/URIBuilder:<init>:(Ljava/lang/String;)V', 1, 41, [pointsTo('this', 'Object[10460]')], 'java/lang/Object:<init>:()V', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 226, 'org/apache/http/client/utils/URIBuilder:<init>:(Ljava/lang/String;)V', 10, 43, [pointsTo('this', 'Object[10460]')], 'java/net/URI:<init>:(Ljava/lang/String;)V', ['https://null']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 228, 'java/net/URI:<init>:(Ljava/lang/String;)V', 1, 44, [pointsTo('this', 'Object[10460]')], 'java/lang/Object:<init>:()V', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 255, 'java/net/URI:<init>:(Ljava/lang/String;)V', 45, 46, [pointsTo('this', 'Object[10460]')], 'java/net/URI$Parser:<init>:(Ljava/net/URI;Ljava/lang/String;)V', ['Object[10469]', 'https://null']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 260, 'java/net/URI$Parser:<init>:(Ljava/net/URI;Ljava/lang/String;)V', 6, 47, [pointsTo('this', 'Object[10460]')], 'java/lang/Object:<init>:()V', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 273, 'java/net/URI$Parser:<init>:(Ljava/net/URI;Ljava/lang/String;)V', 26, 49, [pointsTo('this', 'Object[10460]')], 'java/net/URI:access$002:(Ljava/net/URI;Ljava/lang/String;)Ljava/lang/String;', ['Object[10469]', 'https://null']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 282, 'java/net/URI:<init>:(Ljava/lang/String;)V', 49, 52, [pointsTo('this', 'Object[10460]')], 'java/net/URI$Parser:parse:(Z)V', ['']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 288, 'java/net/URI$Parser:parse:(Z)V', 9, 53, [pointsTo('this', 'Object[10460]')], 'java/lang/String:length:()I', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 299, 'java/net/URI$Parser:parse:(Z)V', 20, 55, [pointsTo('this', 'Object[10460]')], 'java/net/URI$Parser:scan:(IILjava/lang/String;Ljava/lang/String;)I', ['/?#', ':', 5, 58]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 307, 'java/net/URI$Parser:scan:(IILjava/lang/String;Ljava/lang/String;)I', 12, 56, [pointsTo('this', 'Object[10460]')], 'java/net/URI$Parser:charAt:(I)C', [5]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 311, 'java/net/URI$Parser:charAt:(I)C', 5, 57, [pointsTo('this', 'Object[10460]')], 'java/lang/String:charAt:(I)C', [4]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 328, 'java/net/URI$Parser:scan:(IILjava/lang/String;Ljava/lang/String;)I', 20, 60, [pointsTo('this', 'Object[10460]')], 'java/lang/String:indexOf:(I)I', [58]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 332, 'java/lang/String:indexOf:(I)I', 3, 61, [pointsTo('this', 'Object[10460]')], 'java/lang/String:indexOf:(II)I', ['', '']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 1073, 'java/net/URI$Parser:parse:(Z)V', 36, 129, [pointsTo('this', 'Object[10460]')], 'java/net/URI$Parser:at:(IIC)Z', [5, 12, ':']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 1079, 'java/net/URI$Parser:at:(IIC)Z', 7, 130, [pointsTo('this', 'Object[10460]')], 'java/net/URI$Parser:charAt:(I)C', [5]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 1108, 'java/net/URI$Parser:parse:(Z)V', 57, 135, [pointsTo('this', 'Object[10460]')], 'java/net/URI:access$400:()J', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 1112, 'java/net/URI$Parser:parse:(Z)V', 62, 137, [pointsTo('this', 'Object[10460]')], 'java/net/URI$Parser:checkChar:(IJJLjava/lang/String;)V', [0, 0, 'H_ALPHA', 'scheme name']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 1121, 'java/net/URI$Parser:checkChar:(IJJLjava/lang/String;)V', 10, 138, [pointsTo('this', 'Object[10460]')], 'java/net/URI$Parser:checkChars:(IIJJLjava/lang/String;)V', [1, 0, 'H_ALPHA', 'scheme name', 0]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 1127, 'java/net/URI$Parser:checkChars:(IIJJLjava/lang/String;)V', 6, 139, [pointsTo('this', 'Object[10460]')], 'java/net/URI$Parser:scan:(IIJJ)I', ['H_ALPHA', 0, 104, '']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 1135, 'java/net/URI$Parser:scan:(IIJJ)I', 12, 140, [pointsTo('this', 'Object[10460]')], 'java/net/URI$Parser:charAt:(I)C', [4]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 1157, 'java/net/URI$Parser:scan:(IIJJ)I', 22, 144, [pointsTo('this', 'Object[10460]')], 'java/net/URI:access$300:(CJJ)Z', ['h', 0, 'H_ALPHA']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1], 1161, 'java/net/URI:access$300:(CJJ)Z', 3, 145, [pointsTo('this', 'Object[10460]')], 'java/net/URI:match:(CJJ)Z', ['h', 0, 'H_ALPHA']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1], 29, 'java/net/URI$Parser:parse:(Z)V', 77, 155, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)')], 'java/net/URI$Parser:checkChars:(IIJJLjava/lang/String;)V', [5, 'L_SCHEME', 'H_SCHEME', 'scheme name', 1]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 5, 'java/net/URI$Parser:scan:(IIJJ)I', 48, 192, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/net/URI$Parser:scanEscape:(IIC)I', ['t', '', '']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 32, 'java/net/URI$Parser:checkChars:(IIJJLjava/lang/String;)V', 22, 195, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/StringBuilder:<init>:()V', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 46, 'java/net/URI$Parser:checkChars:(IIJJLjava/lang/String;)V', 27, 201, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/StringBuilder:append:(Ljava/lang/String;)Ljava/lang/StringBuilder;', ['scheme name']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 76, 'java/lang/AbstractStringBuilder:ensureCapacityInternal:(I)V', 17, 206, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/AbstractStringBuilder:newCapacity:(I)I', ['']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 97, 'java/lang/AbstractStringBuilder:ensureCapacityInternal:(I)V', 20, 208, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/util/Arrays:copyOf:([CI)[C', [34, 'Object[10479]']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 108, 'java/util/Arrays:copyOf:([CI)[C', 11, 209, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/Math:min:(II)I', [16, 34]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 225, 'java/net/URI$Parser:checkChars:(IIJJLjava/lang/String;)V', 35, 227, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/StringBuilder:toString:()Ljava/lang/String;', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 285, 'java/net/URI$Parser:checkChars:(IIJJLjava/lang/String;)V', 40, 237, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/net/URI$Parser:fail:(Ljava/lang/String;I)V', ['Illegal character in scheme name', 0]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 292, 'java/net/URI$Parser:fail:(Ljava/lang/String;I)V', 10, 238, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/net/URISyntaxException:<init>:(Ljava/lang/String;Ljava/lang/String;I)V', ['https://null', 'Illegal character in scheme name', 0]).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 295, 'java/net/URISyntaxException:<init>:(Ljava/lang/String;Ljava/lang/String;I)V', 2, 239, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/Exception:<init>:(Ljava/lang/String;)V', ['Illegal character in scheme name']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 298, 'java/lang/Exception:<init>:(Ljava/lang/String;)V', 2, 240, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/Throwable:<init>:(Ljava/lang/String;)V', ['Illegal character in scheme name']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 300, 'java/lang/Throwable:<init>:(Ljava/lang/String;)V', 1, 241, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/Object:<init>:()V', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 312, 'java/lang/Throwable:<init>:(Ljava/lang/String;)V', 24, 243, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/Throwable:fillInStackTrace:()Ljava/lang/Throwable;', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 351, 'com/fullteaching/backend/utils/HttpApiClient:<init>:(Lorg/apache/http/impl/client/HttpClientBuilder;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V', 160, 249, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/IllegalArgumentException:<init>:(Ljava/lang/String;Ljava/lang/Throwable;)V', ['Could not create uri', 'Object[10482]']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 355, 'java/lang/IllegalArgumentException:<init>:(Ljava/lang/String;Ljava/lang/Throwable;)V', 3, 250, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/RuntimeException:<init>:(Ljava/lang/String;Ljava/lang/Throwable;)V', ['Could not create uri', 'Object[10482]']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 359, 'java/lang/RuntimeException:<init>:(Ljava/lang/String;Ljava/lang/Throwable;)V', 3, 251, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/Exception:<init>:(Ljava/lang/String;Ljava/lang/Throwable;)V', ['Could not create uri', 'Object[10482]']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 363, 'java/lang/Exception:<init>:(Ljava/lang/String;Ljava/lang/Throwable;)V', 3, 252, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/Throwable:<init>:(Ljava/lang/String;Ljava/lang/Throwable;)V', ['Could not create uri', 'Object[10482]']).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 365, 'java/lang/Throwable:<init>:(Ljava/lang/String;Ljava/lang/Throwable;)V', 1, 253, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/Object:<init>:()V', []).
invokes('com.fullteaching.backend.e2e.rest.UserRestTest:testChangeUserPassword', [1, 1, 2, 1], 377, 'java/lang/Throwable:<init>:(Ljava/lang/String;Ljava/lang/Throwable;)V', 24, 255, [pointsTo('this', 'Object[10460]'), constr('((1099511627776L)&([java/net/URI].java/net/URI:H_ALPHA))!=(0L)'), constr('((4503599627370496L)&([java/net/URI].java/net/URI:H_SCHEME))==(0L)'), constr('(([java/net/URI].java/net/URI:L_SCHEME)&(1L))!=(0L)')], 'java/lang/Throwable:fillInStackTrace:()Ljava/lang/Throwable;', []).
